### ISSUE TITLE
Exodus doorgame server?

### ISSUE THREAD

**Issue by BlaZZZed1980** [haliphax/aperture#2]
Hi!  I know this is a longshot--but I'm trying to get registered for the Exodus doorgame server if it still exists, and I'm not sure my applications are going through.  I know aperture is part of the client package, so I'm hoping you can help me get connected to the server.

**Comment by haliphax** [comment]
They're apparently not getting mailed _at all_. I haven't seen any interest in the platform in almost two years, and I get maybe 5 logins per month. I have plans to migrate it to a different VPS and a new BBS software I wrote myself, but I just haven't had the time. Hit me up directly (haliphax at gmail dot com) and I'll set you up, but I can't guarantee how long the service is going to stay around.
